In [ ]:
import numpy as np#

In [35]:
import numpy as np

arr1 = np.array([10,2,7,5])
#print(arr1)
#print(type(arr1))
#print(np.size(arr1))
# print(arr1.sort())

arr1 = np.append(arr1, [11])
#print(arr1)
arr1 = np.insert(arr1, 0, 9)#print(arr1)

arr1 = np.delete(arr1, 0)
#print(arr1)


arr2 = np.array([[ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])
# print(arr2)
# print(arr2.ndim)
# print(arr2.size)

arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])

arr5 = np.reshape(arr5, (3, 2,2))
print(arr5)
print(arr5.ndim)
print(arr5.size)

arr5 = arr5.reshape(arr5.shape[0],-1)
print(arr5)
print(arr5.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
